#!/bin/sh

ALIASRC=$XDG_CONFIG_HOME/shell/aliasrc

# Shortcut
alias \
  balias='[ -f $ALIASRC ] && $EDITOR $ALIASRC && . $ALIASRC' \
	rm='echo use del!' \
	n='newsboat' \
  m='neomutt' \
  mutt='neomutt' \
  v='nvim' \
  vim='nvim' \
  copy='xclip -selection clipboard' \
  vpnc='sudo protonvpn connect' \
  vpnr='sudo protonvpn reconnect' \
  vpns='protonvpn status' \
  vpnd='sudo protonvpn disconnect' \
  myip='curl ipinfo.io/ip' \
  del='trash-put' \
  cpu='cpupower frequency-info' \
  powersave='sudo cpupower frequency-set -g powersave' \
  performance='sudo cpupower frequency-set -g performance' \
  ondemand='sudo cpupower frequency-set -g ondemand' \
  conservative='sudo cpupower frequency-set -g conservative' \
	freq800='sudo cpupower frequency-set -u 800MHz' \
	freq1200='sudo cpupower frequency-set -u 1200MHz' \
	freq1800='sudo cpupower frequency-set -u 1800MHz' \
	freq2700='sudo cpupower frequency-set -u 2700MHz' \
	xo='f(){ nohup xdg-open "$1" >/dev/null 2>&1 & }; f' \
	silent='f(){ nohup $1 </dev/null >/dev/null 2>&1 & }; f' \
  mkd='mkdir -pv' \
	e='ranger' \
	mycc='c99 -Wall -g -o binary' \
	t='$EDITOR ~/doc/TODO'

# Fix
alias \
  ssh='TERM='"'"'xterm-256color'"'"' ssh' \
	mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc'

# Workspace
alias \
  cduni='cd $HOME/studyspace/uni' \
	s='cd ~/.local/bin' \
	cdelhori='cd ~/workspace/website/elhori.com' \
	cdlinksync='cd ~/workspace/git/linksync' \
	cdgit='cd ~/workspace/git' \
	cdblog4j='cd ~/workspace/git/blog4j'

# System
alias \
  ls='ls --color=auto --group-directories-first' \
  grep='grep --color=auto' \
  diff='diff --color=auto' \
  la='ls -A' \
  l='ls -ACF' \
  ll='ls -alhF'

# Git
alias \
  gits='git status' \
  g='git status' \
  gitl='git log' \
  gitch='git checkout' \
  gitb='git branch' \
  gitd='git diff'

# Docker
alias \
  dkps='docker ps -a' \
  dkr='docker run' \
  dks='docker stop' \
  dkrm='docker rm' \
  dkrmi='docker rmi' \
  dkcu='docker-compose up' \
  dkcd='docker-compose down' \
  dkcr='docker-compose restart'

# Pacman
alias \
	paci='f(){ sudo pacman -S "$@" && notify-send "Pacman" "Package(s) installed"; }; f' \
  pacr='sudo pacman -Rsn' \
  pacu='sudo pacman -Syu --noconfirm && notify-send "Pacman" "System updated"'

# Apt
# alias \
# sai='sudo apt install' \
# sar='sudo apt remove' \
# saar='sudo apt autoremove' \
# uu='sudo apt update && sudo apt upgrade && sudo apt autoremove'
