#!/bin/sh

# Shortcut
alias \
	rm='echo use del!' \
	n='newsboat' \
  m='neomutt' \
  mutt='neomutt' \
  v='nvim' \
  vim='nvim' \
  t='tree' \
  copy='xclip -selection clipboard' \
  vpnc='sudo protonvpn connect' \
  vpnr='sudo protonvpn reconnect' \
  vpns='protonvpn status' \
  vpnd='sudo protonvpn disconnect' \
  myip='curl ipinfo.io/ip' \
  del='trash-put' \
  cpu='cpupower frequency-info' \
  powersave='sudo cpupower frequency-set -g powersave -d 800MHz -u 800MHz' \
  performance='sudo cpupower frequency-set -g performance -d 800MHz -u 2.7GHz' \
  ondemand='sudo cpupower frequency-set -g ondemand -d 800MHz -u 1.8GHz' \
  conservative='sudo cpupower frequency-set -g conservative -d 800MHz -u 1.5GHz' \
	xo='f(){ nohup xdg-open "$1" >/dev/null 2>&1 & }; f' \
	silent='f(){ nohup $1 </dev/null >/dev/null 2>&1 & }; f' \
  mkd='mkdir -pv' \
	g='grep -i' \
	e='ranger' \
	mycc='c99 -Wall -g -o binary' \
	todo='$EDITOR ~/doc/TODO' \
	b='cat /sys/class/power_supply/BAT0/capacity'

# Fix
alias \
  ssh='TERM='"'"'xterm-256color'"'"' ssh' \
	mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc'

# Workspace
ALIASRC=$XDG_CONFIG_HOME/shell/aliasrc
alias \
  balias='[ -f $ALIASRC ] && $EDITOR $ALIASRC && . $ALIASRC' \
  uni='[ -d $HOME/studyspace/uni ] && cd $HOME/studyspace/uni' \
	s='cd ~/.local/bin/script' \
	elhori='cd ~/workspace/website/elhori.com/'

# System
alias \
  ls='ls --color=auto --group-directories-first' \
  grep='grep --color=auto' \
  diff='diff --color=auto' \
  la='ls -A' \
  l='ls -ACF' \
  ll='ls -alhF'

# Git
alias \
  gits='git status' \
  gitl='git log' \
  gitch='git checkout' \
  gitb='git branch' \
  gitd='git diff'

# Docker
alias \
  dkps='docker ps -a' \
  dkr='docker run' \
  dks='docker stop' \
  dkrm='docker rm' \
  dkrmi='docker rmi' \
  dkcu='docker-compose up' \
  dkcd='docker-compose down' \
  dkcr='docker-compose restart'

# Pacman
alias \
	paci='f(){ sudo pacman -S "$@" && notify-send "Pacman" "Package(s) installed"; }; f' \
  pacr='sudo pacman -Rsn' \
  pacu='sudo pacman -Syu && notify-send "Pacman" "System updated"'

# Apt
# alias \
# sai='sudo apt install' \
# sar='sudo apt remove' \
# saar='sudo apt autoremove' \
# uu='sudo apt update && sudo apt upgrade && sudo apt autoremove'
